import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from './providers';
import useDarkMode from "use-dark-mode";



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  //const darkMode = useDarkMode(false);

  return (
    <html lang="en">
      <body className={inter.className} style={{overscrollBehavior:'none'}}>
        <Providers>
            {children}
        </Providers>
      </body>
    </html>
  )
}
